// Gegenereerd uit "zinofonzin-casussen-100-v1" — 10 oefencasussen per les.
// Verdict-codes: 'zin' (alarmbel is vals alarm, claim klopt), 'onzin' (alarmbel is terecht), 'genuanceerd' (context-afhankelijk).

export type CasusVerdict = 'zin' | 'genuanceerd' | 'onzin'

export type Casus = {
  id: string
  afzender: string
  context: string | null
  stelling: string | null
  noot: string | null
  trigger: string
  verdict: CasusVerdict
  uitleg: string
  /** Nog niet ingevuld voor bestaande casussen — komt er per casus een illustratie bij. */
  afbeelding?: string | null
}

export const CASUSSEN_PER_LES: Record<string, Casus[]> = {
  "belang": [
  { id: "belang-1", afzender: "FitMom Lieve", context: "influencer, 320k volgers, verkoopt voedingssupplementen", stelling: "Magnetrons breken voedingsstoffen in je eten af tot zinloze moleculen.", noot: null, trigger: "commercieel belang (haar supplementen \"vervangen\" wat je verliest)", verdict: "onzin", uitleg: "magnetron verwarmt; voedingsstoffen blijven net zo goed als bij koken." },
  { id: "belang-2", afzender: "SlimFit", context: "afslank-app, Instagram-advertentie", stelling: "Onze gebruikers verliezen gemiddeld 5 kilo in 4 weken.", noot: null, trigger: "commercieel belang (verkoopt abonnementen)", verdict: "onzin", uitleg: "zonder controlegroep, selectief gerapporteerd; bij de meeste afslanken houdt het niet aan." },
  { id: "belang-3", afzender: "NS", context: "Nederlandse Spoorwegen, website", stelling: "De trein stoot 75% minder CO₂ uit per reiziger dan de auto.", noot: null, trigger: "eigen belang (klanten naar trein lokken)", verdict: "zin", uitleg: "onafhankelijk bevestigd door CBS en CE Delft." },
  { id: "belang-4", afzender: "Bibliotheek Leiden", context: "Instagram-post", stelling: "Tieners die regelmatig lezen scoren hoger op taal- en woordenschattoetsen.", noot: null, trigger: "eigen belang (promoot lezen)", verdict: "zin", uitleg: "meta-analyses bevestigen dit; belang botst niet met waarheid." },
  { id: "belang-5", afzender: "WhatsApp-bericht", context: "van \"Centrale Bank Helpdesk\"", stelling: "Je rekening is geblokkeerd wegens verdachte activiteit. Klik hier om te verifiëren.", noot: null, trigger: "vijandig belang (oplichting)", verdict: "onzin", uitleg: "phishing, banken sturen nooit zulke links." },
  { id: "belang-6", afzender: "Klimaat-NGO \"Genoeg\"", context: "Instagram-video", stelling: "De vleesindustrie veroorzaakt meer broeikasgassen dan al het transport bij elkaar.", noot: null, trigger: "ideologisch belang", verdict: "genuanceerd", uitleg: "volgens IPCC schommelt veeteelt rond ~12-18%, transport ~14-16%; afhankelijk van wat je meeneemt klopt het of niet helemaal." },
  { id: "belang-7", afzender: "Oom op verjaardag", context: "werkt 30 jaar in de bouw", stelling: "Geloof me, die zonnepanelen verdien je nooit terug.", noot: null, trigger: "persoonlijke ervaring/frustratie, niet representatief", verdict: "onzin", uitleg: "onzin in algemene zin — terugverdientijd in NL is gemiddeld 7-10 jaar." },
  { id: "belang-8", afzender: "Zonnepanelen-bedrijf", context: "brief in de bus", stelling: "Met onze installatie verdien je binnen 5 jaar je investering terug.", noot: null, trigger: "commercieel belang (acquisitie)", verdict: "genuanceerd", uitleg: "kan kloppen of niet, afhankelijk van dakhelling, schaduw, eigen gebruik." },
  { id: "belang-9", afzender: "Politiebond", context: "in een nieuwsuitzending", stelling: "Het aantal geweldsincidenten op straat is in vijf jaar verdrievoudigd.", noot: null, trigger: "eigen belang (meer agenten/budget)", verdict: "onzin", uitleg: "onzin meestal — CBS-cijfers tonen geen verdrievoudiging; politiebond heeft motief tot dramatiseren." },
  { id: "belang-10", afzender: "Anonieme Telegram-kanaal", context: "\"WAARheid.nl\"", stelling: "Het OMT heeft de coronacijfers tijdens de pandemie vervalst.", noot: null, trigger: "vijandig belang (desinformatie/verdeeldheid)", verdict: "onzin", uitleg: "meerdere onafhankelijke audits hebben dit weerlegd." },
  ],
  "gezag": [
  { id: "gezag-1", afzender: "Tv-kok", context: "interview in een talkshow over klimaat", stelling: "De klimaatcrisis is overdreven, planten houden juist van CO₂.", noot: null, trigger: "buiten vakgebied", verdict: "onzin", uitleg: "koks zijn geen klimaatwetenschappers; planten \"houden\" van CO₂ is een verkeerd-begrepen losse waarneming." },
  { id: "gezag-2", afzender: "Topvoetballer", context: "Instagram-post", stelling: "Vaccins veroorzaken autisme bij kinderen.", noot: null, trigger: "geen medische scholing", verdict: "onzin", uitleg: "weerlegd door tientallen grote studies; de oorspronkelijke Wakefield-studie is ingetrokken." },
  { id: "gezag-3", afzender: "Tandarts", context: "brochure in eigen praktijk", stelling: "Fluoride in tandpasta beschermt tegen cariës.", noot: null, trigger: "binnen vakgebied", verdict: "zin", uitleg: "meer dan 70 jaar evidentie ondersteunt dit." },
  { id: "gezag-4", afzender: "Astrofysicus", context: "podcast over de Nederlandse economie", stelling: "De staatsschuld is op deze koers onhoudbaar.", noot: null, trigger: "buiten vakgebied", verdict: "genuanceerd", uitleg: "claim kan kloppen, maar afzender heeft geen expertise; economen verschillen hier zelf van mening." },
  { id: "gezag-5", afzender: "KNMI", context: "website", stelling: "April 2026 was de warmste april ooit gemeten in Nederland.", noot: null, trigger: "binnen vakgebied", verdict: "zin", uitleg: "KNMI is de gezaghebbende bron voor weerstatistieken." },
  { id: "gezag-6", afzender: "Lifestyle-influencer", context: "TikTok-video", stelling: "Detox-thee zuivert je lever in zeven dagen.", noot: null, trigger: "geen medische opleiding", verdict: "onzin", uitleg: "je lever zuivert zichzelf; \"detox-thee\" heeft geen aantoonbaar effect." },
  { id: "gezag-7", afzender: "Hoogleraar virologie", context: "NOS-interview", stelling: "Een hoge prikbereidheid beschermt ook ongevaccineerden via groepsimmuniteit.", noot: null, trigger: "binnen vakgebied", verdict: "zin", uitleg: "basisbegrip in de epidemiologie." },
  { id: "gezag-8", afzender: "Sportcommentator", context: "column over geschiedenis", stelling: "De Tweede Wereldoorlog werd gewonnen omdat democratie nu eenmaal sterker is dan dictatuur.", noot: null, trigger: "buiten vakgebied", verdict: "onzin", uitleg: "historisch te simpel; meer factoren (industriële capaciteit, geografie, allianties)." },
  { id: "gezag-9", afzender: "Persoonlijke fitnesstrainer", context: "voedingsadvies", stelling: "Je moet 6 maaltijden per dag eten om je metabolisme op gang te houden.", noot: null, trigger: "geen voedingsdeskundige", verdict: "onzin", uitleg: "mythe, weerlegd door meerdere studies." },
  { id: "gezag-10", afzender: "Filmreviewer", context: "bespreking van Interstellar", stelling: "De zwarte gaten in de film kloppen wetenschappelijk.", noot: null, trigger: "buiten vakgebied", verdict: "genuanceerd", uitleg: "claim klopt feitelijk (Kip Thorne adviseerde), maar afzender herhaalt het zonder eigen expertise." },
  ],
  "herkomst": [
  { id: "herkomst-1", afzender: "Klasgenoot", context: "in de pauze", stelling: "Mijn neef werkt bij Apple en die zegt dat de iPhone 17 al uitgesteld is.", noot: null, trigger: "vriend-van-vriend-van-vriend, onverifieerbaar", verdict: "onzin", uitleg: "anonieme tweedehands-claim; Apple communiceert lekken zelden via familieleden." },
  { id: "herkomst-2", afzender: "WhatsApp-ketenbericht", context: "doorgestuurd in familiegroep", stelling: "Volgens dr. Kramer van het AMC zou paracetamol gevaarlijker zijn dan eerder gedacht.", noot: null, trigger: "AMC bestaat niet meer (= Amsterdam UMC), naam Kramer onvindbaar in zoekresultaten", verdict: "onzin", uitleg: "onzin." },
  { id: "herkomst-3", afzender: "Nieuwsplatform \"Klimaat-actueel\"", context: "artikel", stelling: "Volgens onderzoek van Oxford University is hernieuwbare energie nu goedkoper dan steenkool.", noot: "geen link, geen auteursnaam, geen jaartal", trigger: "bron onvindbaar", verdict: "genuanceerd", uitleg: "claim klopt deels (IEA en Lazard), maar afzender geeft geen handvat om dat zelf na te kijken." },
  { id: "herkomst-4", afzender: "Reddit-post", context: "anoniem account", stelling: "Een dokter in mijn ziekenhuis vertelde me dat...", noot: null, trigger: "anoniem, geen ziekenhuis genoemd, niet traceerbaar", verdict: "onzin", uitleg: "typische broken-source-claim." },
  { id: "herkomst-5", afzender: "NOS-artikel", context: "met link naar CBS-rapport", stelling: "Volgens cijfers van het CBS daalde de werkloosheid met 0,3% in maart 2026.", noot: null, trigger: "claim wordt doorgegeven (NOS, niet CBS), maar bron is direct vindbaar", verdict: "zin", uitleg: "herkomst is traceerbaar." },
  { id: "herkomst-6", afzender: "Wikipedia-pagina", context: "over recycling", stelling: "De gemiddelde levensduur van een rugzak is 4 jaar.", noot: "voetnoot leidt naar een blog die geen bron geeft", trigger: "circulaire bron — bron verwijst naar bron die nergens uit komt", verdict: "onzin", uitleg: "niet onderbouwd." },
  { id: "herkomst-7", afzender: "Klimaatactivist", context: "op Instagram", stelling: "97% van klimaatwetenschappers is het erover eens dat de mens de opwarming veroorzaakt.", noot: null, trigger: "afzender geeft claim door zonder bron", verdict: "zin", uitleg: "claim is bekend en onderbouwd (Cook et al. 2013; meerdere replicaties), maar de afzender hoort die bron erbij te leveren." },
  { id: "herkomst-8", afzender: "Buurman over geruchten in de wijk", context: null, stelling: "Mijn vrouw heeft het van haar collega — de buurt krijgt een asielzoekerscentrum.", noot: null, trigger: "dubbel-tweedehands", verdict: "onzin", uitleg: "onzin meestal — gemeenteplannen worden via gemeente gecommuniceerd, niet via buurvrouw-van-collega." },
  { id: "herkomst-9", afzender: "Quest", context: "(tijdschrift) — artikel over slaap", stelling: "Onderzoek toont aan dat een uur extra slaap je productiever maakt.", noot: "geen bronvermelding aan het einde van het artikel", trigger: "claim hangt in de lucht, geen vindplaats", verdict: "genuanceerd", uitleg: "claim klopt waarschijnlijk, maar zonder bron kan de lezer het niet checken." },
  { id: "herkomst-10", afzender: "Wetenschappelijk artikel", context: "peer-reviewed journal", stelling: "In Smith et al. (2022) werd aangetoond dat... (volledige citatie in voetnoot)", noot: null, trigger: "tweedehands claim, met traceerbare bron", verdict: "zin", uitleg: "exact zo hoort het." },
  ],
  "onderbouwing": [
  { id: "onderbouwing-1", afzender: "Hondenvoer-producent", context: "verpakking", stelling: "Onze hond at dit voer en werd 18 jaar oud — bewijs dat het beter is.", noot: null, trigger: "n = 1", verdict: "onzin", uitleg: "één hond is geen bewijs." },
  { id: "onderbouwing-2", afzender: "Klimaatscepticus-blog", context: null, stelling: "2024 was kouder dan 1998 — dus de opwarming is voorbij.", noot: null, trigger: "cherry-picking (één jaar tegenover trend)", verdict: "onzin", uitleg: "klimaattrend wordt gemeten over 30 jaar, niet 1." },
  { id: "onderbouwing-3", afzender: "Crème-influencer", context: "voor/na-foto op Instagram", stelling: "Deze crème werkt — kijk maar.", noot: null, trigger: "één foto, geen blindering, mogelijk filter/belichting", verdict: "onzin", uitleg: "onzin als bewijs — kan kloppen, maar bewijs is waardeloos." },
  { id: "onderbouwing-4", afzender: "RIVM-rapport", context: "over rioolwatermonitoring", stelling: "Op basis van wekelijkse metingen in 380 rioolwater-meetpunten...", noot: null, trigger: "methodologie uitgebreid beschreven", verdict: "zin", uitleg: "model-bewijs." },
  { id: "onderbouwing-5", afzender: "Politicus", context: "in een debat", stelling: "Sinds we deze maatregel invoerden, is criminaliteit met 12% gedaald.", noot: null, trigger: "één trend-claim, geen vergelijking", verdict: "genuanceerd", uitleg: "kan kloppen, maar correlatie ≠ causaliteit (kan ook door andere factoren)." },
  { id: "onderbouwing-6", afzender: "Wantrouwen-website", context: null, stelling: "Bij die ziekte krijgen 90% van de patiënten complicaties.", noot: null, trigger: "percentage zonder bron, populatie, of tijdsraam", verdict: "onzin", uitleg: "getal is leeg zonder context." },
  { id: "onderbouwing-7", afzender: "Afslankthee-reclame", context: null, stelling: "Onafhankelijk getest: 4 op 5 vrouwen geeft aan tevreden te zijn.", noot: null, trigger: "\"onafhankelijk getest\" zonder N, methode of bron", verdict: "onzin", uitleg: "typisch marketing-frame zonder onderbouwing." },
  { id: "onderbouwing-8", afzender: "Krant", context: "artikel over verkeersveiligheid", stelling: "Volgens CBS-data daalde het aantal verkeersdoden in 2024 met 8%.", noot: null, trigger: "helder getal, gerefereerd aan gezaghebbende bron", verdict: "zin", uitleg: "zin." },
  { id: "onderbouwing-9", afzender: "Sport-coach", context: "in zijn cv", stelling: "Mijn methode werkt — alle topvoetballers die ik trainde haalden de eredivisie.", noot: null, trigger: "survivorship bias (de honderden die het níet haalden tellen niet mee)", verdict: "onzin", uitleg: "onzin." },
  { id: "onderbouwing-10", afzender: "Wetenschapper", context: "op een congres", stelling: "Onze meta-analyse van 87 studies (N = 120.000) toont een gemiddeld effect van 0,4 standaarddeviatie.", noot: null, trigger: "brede bewijsbasis, kwantificeerbaar", verdict: "zin", uitleg: "zin." },
  ],
  "logica": [
  { id: "logica-1", afzender: "Internetforum-post", context: null, stelling: "Als we minder vlees eten, moeten boeren hun werk opgeven en stort de economie in.", noot: null, trigger: "hellend vlak", verdict: "onzin", uitleg: "geen automatische causale keten." },
  { id: "logica-2", afzender: "Talkshow-gast", context: null, stelling: "Of je bent vóór strikte regels op sociale media, of je staat achter zelfmoord onder jongeren.", noot: null, trigger: "zwart-witdenken", verdict: "onzin", uitleg: "er zijn talloze tussenposities." },
  { id: "logica-3", afzender: "Columnist", context: "in een krant", stelling: "Klimaatwetenschappers vinden dat je nooit meer mag vliegen.", noot: null, trigger: "strohond — vereenvoudigt en verdraait wat wetenschappers feitelijk zeggen (minder vliegen, niet nooit)", verdict: "onzin", uitleg: "onzin." },
  { id: "logica-4", afzender: "Schoolforum", context: null, stelling: "Sinds die nieuwe leraar er is, zijn de cijfers gedaald. Hij verpest het.", noot: null, trigger: "post hoc (correlatie ≠ causaliteit)", verdict: "onzin", uitleg: "kan ook door zwaardere stof, andere leerlingen, examentijd." },
  { id: "logica-5", afzender: "Politicus", context: "in interview", stelling: "Als we het rookverbod verder uitbreiden, eindigen we in een politiestaat.", noot: null, trigger: "hellend vlak", verdict: "onzin", uitleg: "rookverbod en politiestaat verbinden vergt vele tussenstappen die niet automatisch volgen." },
  { id: "logica-6", afzender: "Wiskundeleraar", context: "in de klas", stelling: "Als je drie zijden van een driehoek kent, kun je alle hoeken berekenen.", noot: null, trigger: "logische conclusie wordt verklaard", verdict: "zin", uitleg: "wiskundig correct." },
  { id: "logica-7", afzender: "Discussiepartner", context: "op een feestje", stelling: "Wetenschappers waren het 40 jaar geleden óók niet eens over koolstof. Dus kunnen we ze nu ook niet vertrouwen.", noot: null, trigger: "drogreden (overgeneralisatie)", verdict: "onzin", uitleg: "wetenschap herziet zichzelf, dat is een kracht, geen zwakte." },
  { id: "logica-8", afzender: "Manager", context: "op werk", stelling: "We kunnen óf het project op tijd opleveren, óf met kwaliteit. Niet beide.", noot: null, trigger: "zwart-wit (vaak is er een derde optie of een middenweg)", verdict: "genuanceerd", uitleg: "kan kloppen in extreme tijdsdruk, maar wordt vaak overdreven gebruikt." },
  { id: "logica-9", afzender: "Anti-vaccin-website", context: null, stelling: "Mijn zoon kreeg een vaccin en raakte autistisch. Het vaccin heeft hem autistisch gemaakt.", noot: null, trigger: "post hoc — sequentie wordt verward met oorzaak", verdict: "onzin", uitleg: "autisme-symptomen worden vaak rond dezelfde leeftijd zichtbaar als vaccinatiemoment; geen causaal verband aangetoond." },
  { id: "logica-10", afzender: "Detective", context: "in een rechtszaak", stelling: "De verdachte was op de plaats delict, had het motief, en zijn DNA werd aangetroffen op het wapen. Daarom is hij verdachte nr. 1.", noot: null, trigger: "opgebouwde redenering met meerdere onafhankelijke pijlers", verdict: "zin", uitleg: "keten van bewijs (geen drogreden)." },
  ],
  "te-simpel-of-te-zeker": [
  { id: "te-simpel-of-te-zeker-1", afzender: "Online afslank-coach", context: null, stelling: "Iedereen die dit programma 30 dagen volgt, valt af. Gegarandeerd.", noot: null, trigger: "te zeker — geen menselijk programma werkt bij iedereen", verdict: "onzin", uitleg: "onzin." },
  { id: "te-simpel-of-te-zeker-2", afzender: "Politicus", context: "in campagne-spotje", stelling: "Als we de migratie stoppen, lossen we alle problemen op.", noot: null, trigger: "één-oplossing-claim", verdict: "onzin", uitleg: "sociale problemen hebben meervoudige oorzaken." },
  { id: "te-simpel-of-te-zeker-3", afzender: "Reclame", context: "voor cursus", stelling: "Dit programma werkt 100% van de tijd. Anders krijg je je geld terug.", noot: null, trigger: "te zeker", verdict: "onzin", uitleg: "\"geld terug\" is verzekering, geen bewijs van werking." },
  { id: "te-simpel-of-te-zeker-4", afzender: "Influencer", context: "op TikTok", stelling: "De waarheid is simpel: de overheid wil je niet vrij.", noot: null, trigger: "simplificatie van complexe maatschappij", verdict: "onzin", uitleg: "verschillende overheidsdiensten met verschillende motieven." },
  { id: "te-simpel-of-te-zeker-5", afzender: "Wetenschappelijk paper", context: "abstract", stelling: "Vaccinaties zijn effectief, maar niet 100%; bij sommige patiënten treedt verminderde immuunrespons op.", noot: null, trigger: "claim is genuanceerd", verdict: "zin", uitleg: "goed gekalibreerd taalgebruik." },
  { id: "te-simpel-of-te-zeker-6", afzender: "Schoonmaakmiddel-reclame", context: null, stelling: "Doodt 99,9% van bacteriën.", noot: null, trigger: "\"99,9%\" is vaak in labcondities op niet-poreuze oppervlakken", verdict: "genuanceerd", uitleg: "getal klopt maar geldt niet voor jouw aanrecht." },
  { id: "te-simpel-of-te-zeker-7", afzender: "Klimaatscepticus", context: "op podcast", stelling: "De zon bepaalt het klimaat. CO₂ heeft er niets mee te maken.", noot: null, trigger: "één-oorzaak-claim", verdict: "onzin", uitleg: "zon én CO₂ én andere factoren samen." },
  { id: "te-simpel-of-te-zeker-8", afzender: "Hoogleraar", context: "in NPO-radio", stelling: "Op basis van huidige data is het zeer waarschijnlijk dat...", noot: null, trigger: "kalibratie (\"zeer waarschijnlijk\" i.p.v. \"zeker\")", verdict: "zin", uitleg: "goed wetenschappelijk taalgebruik." },
  { id: "te-simpel-of-te-zeker-9", afzender: "Wellness-influencer", context: null, stelling: "Drink ALTIJD 3 liter water per dag — geen uitzonderingen.", noot: null, trigger: "universele claim zonder uitzonderingen", verdict: "onzin", uitleg: "varieert per gewicht, activiteit, klimaat; te veel kan zelfs gevaarlijk zijn." },
  { id: "te-simpel-of-te-zeker-10", afzender: "RIVM", context: "voedingsadvies", stelling: "Het advies om groente te eten geldt voor de meeste mensen, maar er zijn uitzonderingen voor specifieke aandoeningen.", noot: null, trigger: "claim erkent uitzonderingen", verdict: "zin", uitleg: "zin." },
  ],
  "vaag-of-oncontroleerbaar": [
  { id: "vaag-of-oncontroleerbaar-1", afzender: "Wellness-influencer", context: "Instagram", stelling: "Dit oliepje balanceert je energieën.", noot: null, trigger: "wat zijn \"energieën\"? Niet meetbaar", verdict: "onzin", uitleg: "niet falsifieerbaar." },
  { id: "vaag-of-oncontroleerbaar-2", afzender: "Politicus", context: "in tv-debat", stelling: "Wij zorgen voor een rechtvaardiger maatschappij.", noot: null, trigger: "\"rechtvaardiger\" volgens wie, op welke schaal, hoe gemeten?", verdict: "genuanceerd", uitleg: "geen leugen, wel inhoudloos zonder verdere uitwerking." },
  { id: "vaag-of-oncontroleerbaar-3", afzender: "Astrologie-app", context: "push-notificatie", stelling: "Mercurius retrograde zorgt dat je communicatie vandaag niet vlekkeloos verloopt.", noot: null, trigger: "gemaakt zodat élke communicatieproblem het bevestigt", verdict: "onzin", uitleg: "onzin." },
  { id: "vaag-of-oncontroleerbaar-4", afzender: "Onderzoeker", context: "methode-sectie van een paper", stelling: "Onze hypothese voorspelt dat groep A 15% beter presteert dan groep B op test X.", noot: null, trigger: "claim is falsifieerbaar — als groep A níet 15% beter scoort, is hypothese weerlegd", verdict: "zin", uitleg: "zin." },
  { id: "vaag-of-oncontroleerbaar-5", afzender: "Mental-coach", context: "workshop", stelling: "Deze training maakt je mentaal sterker.", noot: null, trigger: "\"mentaal sterker\" niet geoperationaliseerd", verdict: "genuanceerd", uitleg: "kan kloppen, maar zonder definitie niet toetsbaar." },
  { id: "vaag-of-oncontroleerbaar-6", afzender: "Voedingsdeskundige", context: "boek", stelling: "Eet meer groenten — dat is bewezen gezond.", noot: null, trigger: "claim is breed maar wel verbinding naar specifiek bewijs mogelijk", verdict: "zin", uitleg: "algemeen maar onderbouwd." },
  { id: "vaag-of-oncontroleerbaar-7", afzender: "Esoterische gids", context: "webshop crystal healing", stelling: "Het kristal heelt op een diep emotioneel niveau.", noot: null, trigger: "niet observeerbaar, niet meetbaar", verdict: "onzin", uitleg: "onzin." },
  { id: "vaag-of-oncontroleerbaar-8", afzender: "Politicus", context: "campagne-slogan", stelling: "Wij staan voor verandering.", noot: null, trigger: "verandering van wat naar wat? Inhoudloos", verdict: "genuanceerd", uitleg: "niet onwaar, maar ook geen toetsbare claim." },
  { id: "vaag-of-oncontroleerbaar-9", afzender: "Coach", context: "op LinkedIn", stelling: "Mijn relatie veranderde toen ik mijn karma hervond.", noot: null, trigger: "\"karma hervinden\" niet definieerbaar", verdict: "onzin", uitleg: "onzin." },
  { id: "vaag-of-oncontroleerbaar-10", afzender: "Onderzoeker", context: "methode-sectie", stelling: "We meten subjectief welbevinden via een gevalideerde 5-itemschaal (Diener et al., 1985).", noot: null, trigger: "claim is geoperationaliseerd via een schaal", verdict: "zin", uitleg: "zin." },
  ],
  "manipulatie": [
  { id: "manipulatie-1", afzender: "WhatsApp-bericht", context: null, stelling: "VERSPREID DIT! Anders gebeurt er iets met je familie.", noot: null, trigger: "angst-manipulatie", verdict: "onzin", uitleg: "onzin." },
  { id: "manipulatie-2", afzender: "Campagne-advertentie", context: null, stelling: "Wij beschermen je kinderen. De tegenstander niet.", noot: null, trigger: "angst + dehumanisering tegenstander", verdict: "onzin", uitleg: "emotionele framing zonder inhoudelijk argument." },
  { id: "manipulatie-3", afzender: "AI-deepfake-video", context: "van een minister, viral", stelling: "Beste burgers, vanaf volgende maand stoppen we met onderwijssubsidies.", noot: null, trigger: "AI als manipulatiemiddel + valse autoriteit", verdict: "onzin", uitleg: "onzin." },
  { id: "manipulatie-4", afzender: "Goed-doel-advertentie", context: null, stelling: "Voor maar €10 per maand kun je het leven van een kind veranderen.", noot: null, trigger: "emotioneel frame, maar mogelijk waar", verdict: "zin", uitleg: "zin als organisatie betrouwbaar is (controleer via ANBI-status of CBF-keurmerk)." },
  { id: "manipulatie-5", afzender: "Sociale-media-post", context: "met dramatische dier-foto", stelling: "Als je ECHT om dieren geeft, deel je deze post.", noot: null, trigger: "schuld + groepsdruk", verdict: "onzin", uitleg: "manipulatieve framing; delen helpt geen dieren." },
  { id: "manipulatie-6", afzender: "Klasgenoot", context: "in groepschat", stelling: "Iedereen die niet meedoet met de spijbel-actie is een loser.", noot: null, trigger: "groepsdruk", verdict: "onzin", uitleg: "onzin als argument." },
  { id: "manipulatie-7", afzender: "Religieuze leider", context: "in een speech", stelling: "Wie aan onze leer twijfelt, twijfelt aan de waarheid zelf.", noot: null, trigger: "autoriteitsdruk + cirkelredenering", verdict: "onzin", uitleg: "onzin." },
  { id: "manipulatie-8", afzender: "Verzekeringsadvertentie", context: null, stelling: "Wat als jij plotseling wegvalt? Wie zorgt dan voor je kinderen?", noot: null, trigger: "angst-framing", verdict: "genuanceerd", uitleg: "manipulatie, maar het onderliggende risico is wél reëel." },
  { id: "manipulatie-9", afzender: "Wetenschappelijk artikel", context: "discussiesectie", stelling: "Onze data laat een effect zien — maar het effect is klein en context-afhankelijk.", noot: null, trigger: "emotieloos, met nuance", verdict: "zin", uitleg: "zin." },
  { id: "manipulatie-10", afzender: "AI-gegenereerde nepfoto", context: "van een protestbijeenkomst, op Twitter", stelling: "Kijk hoeveel mensen het ermee eens zijn!", noot: null, trigger: "AI-content als bewijs voor populariteit", verdict: "onzin", uitleg: "onzin." },
  ],
  "verspreidingskracht": [
  { id: "verspreidingskracht-1", afzender: "TikTok-clip", context: "met dramatische thumbnail", stelling: "DIT wil je niet missen — wat scholen je nooit vertellen!", noot: null, trigger: "clickbait-frame (geheim + emotie + algemeenheid)", verdict: "genuanceerd", uitleg: "vorm verdacht, inhoud onbekend zonder kijken; meestal teleurstellend." },
  { id: "verspreidingskracht-2", afzender: "WhatsApp-ketenbericht", context: null, stelling: "Stuur dit door naar 10 vrienden, anders krijg je 7 jaar pech.", noot: null, trigger: "urban legend / chain-letter-mechanisme", verdict: "onzin", uitleg: "pre-internet variant, nog steeds dezelfde structuur." },
  { id: "verspreidingskracht-3", afzender: "Nieuwskop", context: null, stelling: "Je gelooft niet wat deze leerling tegen de minister zei!", noot: null, trigger: "clickbait-zin met curiosity gap", verdict: "genuanceerd", uitleg: "vorm misleidend, claim onbekend." },
  { id: "verspreidingskracht-4", afzender: "Reddit-post", context: "viral op r/AmITheAsshole", stelling: "Ik werkte bij KFC en dit is wat je nooit moet bestellen...", noot: null, trigger: "viraal door verontwaardiging + insider-frame", verdict: "genuanceerd", uitleg: "kan oprecht zijn of viraal-jagen; zonder bevestiging onbetrouwbaar." },
  { id: "verspreidingskracht-5", afzender: "NOS-artikel", context: null, stelling: "Onderzoek toont dat slaapgebrek vergeetachtigheid veroorzaakt.", noot: null, trigger: "feitelijk artikel, geen virale framing", verdict: "zin", uitleg: "zin." },
  { id: "verspreidingskracht-6", afzender: "TikTok-trend", context: null, stelling: "Doe de cinnamon challenge — alle creators doen het!", noot: null, trigger: "groepsdynamiek + viraal ontwerp", verdict: "onzin", uitleg: "onzin als advies — fysiek gevaarlijk, virale prikkel zonder zorgwaarde." },
  { id: "verspreidingskracht-7", afzender: "Instagram-account", context: "\"WistJeDat...\"", stelling: "Wist je dat de Eiffeltoren 's zomers 15 cm groter is door warmte-uitzetting?", noot: null, trigger: "viraal-vriendelijk format", verdict: "zin", uitleg: "feit klopt; viraal format is hier oké want het is een kennisfeitje." },
  { id: "verspreidingskracht-8", afzender: "Sociale-media-post", context: "met emotie + dreiging", stelling: "Pas op met dit — mijn vriendin overleed bijna!", noot: null, trigger: "emotie + viraal frame", verdict: "genuanceerd", uitleg: "kan oprecht zijn of viraal-jagen; vereist bron-check." },
  { id: "verspreidingskracht-9", afzender: "CBS-publicatie", context: null, stelling: "Het aantal alleenstaanden steeg met 3% in 2024.", noot: null, trigger: "feitelijk, geen viraal-ontwerp", verdict: "zin", uitleg: "zin." },
  { id: "verspreidingskracht-10", afzender: "Influencer-video", context: "\"5 dingen die je leven veranderen\"", stelling: "DEZE 5 sectjes per dag zullen je leven veranderen!", noot: null, trigger: "listicle + transformatie-belofte = klassiek viraal", verdict: "genuanceerd", uitleg: "vorm zegt: ga twijfelen; inhoud per \"sectje\" check je apart." },
  ],
  "echt-of-nep-ai": [
  { id: "echt-of-nep-ai-1", afzender: "ChatGPT-antwoord", context: "op een huiswerkvraag", stelling: "Volgens artikel 4 lid 2 van de Wet op het Voortgezet Onderwijs...", noot: "artikel bestaat niet", trigger: "AI-hallucinatie van een wetsartikel", verdict: "onzin", uitleg: "onzin." },
  { id: "echt-of-nep-ai-2", afzender: "AI-tekst", context: "in een persbericht", stelling: "Onderzoek van TU Delft (2024) toont aan dat groene autobanden 8% brandstof besparen.", noot: "onderzoek niet vindbaar in TU Delft-database", trigger: "gefabriceerde bron", verdict: "onzin", uitleg: "onzin." },
  { id: "echt-of-nep-ai-3", afzender: "Deepfake-video", context: "van een minister op X", stelling: "Vanaf volgende maand schaffen we de studiefinanciering af.", noot: null, trigger: "AI-gegenereerd audio + beeld", verdict: "onzin", uitleg: "onzin." },
  { id: "echt-of-nep-ai-4", afzender: "AI-vertaling", context: "van een Engelse studiehandleiding", stelling: "De student dient aanwezig te zijn...", noot: null, trigger: "AI-output zonder menselijke check", verdict: "genuanceerd", uitleg: "vaak goed, kan vertaalfouten bevatten op vakjargon." },
  { id: "echt-of-nep-ai-5", afzender: "Profielfoto", context: "op dating-app, AI-gegenereerd", stelling: null, noot: null, trigger: "AI-gegenereerd gezicht — mogelijke catfishing", verdict: "onzin", uitleg: "onzin als identiteitsweergave." },
  { id: "echt-of-nep-ai-6", afzender: "AI-illustratie", context: "bij een nieuwsartikel over klimaatprotest", stelling: null, noot: null, trigger: "AI-art duidelijk als illustratie gepresenteerd", verdict: "zin", uitleg: "context maakt duidelijk dat dit illustratief is, niet documentair." },
  { id: "echt-of-nep-ai-7", afzender: "ChatGPT", context: "beantwoordt: \"Wie is de premier van Nederland?\"", stelling: null, noot: "antwoord uit pre-cutoff data, mogelijk verouderd", trigger: "AI gebruikt verouderde kennis", verdict: "genuanceerd", uitleg: "kan kloppen, kan verouderd zijn; check via actuele bron." },
  { id: "echt-of-nep-ai-8", afzender: "AI-chatbot", context: "op website webshop", stelling: "Wij hebben 24/7 service en geen wachtrij.", noot: null, trigger: "AI-output, maar over eigen bedrijfsproces", verdict: "zin", uitleg: "zin als het bedrijf dit daadwerkelijk regelt." },
  { id: "echt-of-nep-ai-9", afzender: "ChatGPT", context: "verwijst naar een boek met ISBN", stelling: "In *Cognitive Patterns in Adolescents* (Hagberg, 2019, ISBN 978-90-...", noot: "ISBN bestaat niet, boek bestaat niet", trigger: "AI-hallucinatie van bron", verdict: "onzin", uitleg: "onzin." },
  { id: "echt-of-nep-ai-10", afzender: "AI-gegenereerde nieuwspresentator", context: "op een betaaldienst", stelling: "volledig AI-anchor leest echte nieuwsberichten voor", noot: null, trigger: "AI-presentatie, content kan kloppen", verdict: "genuanceerd", uitleg: "vorm is AI, inhoud apart te checken." },
  ],
}
